-   id: svgo
    name: svgo
    entry: svgo
    language: node
    files: \.svg$
    args: []

    # Use additional_dependencies to install the actual node package
    additional_dependencies: ['svgo@3.1.0']
    minimum_pre_commit_version: 0.7.0
